deps: add support for building server with musl
The libraries required for the client are not enabled for Linux, since
it's not possible to static link the OpenGL library (it is a .so
provided by the driver vendor).

diff --git a/deps/pkg/cmake-toolchain/build b/deps/pkg/cmake-toolchain/build
--- a/deps/pkg/cmake-toolchain/build
+++ b/deps/pkg/cmake-toolchain/build
@@ -15,16 +15,30 @@ if [ "x${MSYSTEM-}" = "xMINGW32" ]; then
 	rootpath=$(cd "${prefix}"; pwd -W)
 fi
 
-cat <<EOF >${prefix}/CMake-${host_triplet}.toolchain
+case ${host_triplet} in
+*mingw*)
+	sysname=Windows
+	;;
+*linux*)
+	sysname=Linux
+	;;
+*)
+	echo "ERROR: unknown system type"
+	exit 1
+	;;
+esac
+
+toolchain=${prefix}/cmake-toolchain
+
+cat <<EOF >${toolchain}
 # Toolchain file for cross compilation with CMake
 # THIS FILE IS AUTOMATICALLY GENERATED
 
-SET(CMAKE_SYSTEM_NAME Windows)
+SET(CMAKE_SYSTEM_NAME ${sysname})
 SET(CMAKE_SYSTEM_PROCESSOR ${arch})
 
 SET(CMAKE_C_COMPILER ${CC})
 SET(CMAKE_CXX_COMPILER ${CXX})
-SET(CMAKE_RC_COMPILER ${WINDRES})
 
 SET(CMAKE_FIND_ROOT_PATH ${rootpath})
 
@@ -32,5 +46,9 @@ SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
 SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
 SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
 EOF
+
+if [ "x${WINDRES-}" != x ]; then
+	echo "SET(CMAKE_RC_COMPILER ${WINDRES})" >> ${toolchain}
+fi
 
 cd "${deps}"; rm -rf "${work}"
